### ISSUE TITLE
VnV Plan review

### ISSUE THREAD

**Issue by gabrielasd** [gabrielasd/eomee#10]
Hello @tingyuw,

Could you take a look at my VnV Plan?
You can find the document here: 
https://github.com/gabrielasd/eomee/tree/cas741/docs/VnVPlan 
In particular, could you review my functional and nonfunctional system tests?

Thanks

**Comment by gabrielasd** [comment]
Hi @moalaa,
I've uploaded the VnV Plan's first draft (https://github.com/gabrielasd/eomee/tree/cas741/docs/VnVPlan)
Could you review it? In particular, could you check my verification plans (section 4)?

Tank you

**Comment by gabrielasd** [comment]
Hi Dr. @smiths,
Please could you review my VnV Plan (https://github.com/gabrielasd/eomee/tree/cas741/docs/VnVPlan)?
Do the nonfunctional system tests seem adecuate to you, in particular subsections 5.2.1 and 5.2.2?

Thanks

**Comment by moalaa** [comment]
> Hi @moalaa,
> I've uploaded the VnV Plan's first draft (https://github.com/gabrielasd/eomee/tree/cas741/docs/VnVPlan)
> Could you review it? In particular, could you check my verification plans (section 4)?
> 
> Tank you

Hello Gaby,

I think Dr. @smiths  mentioned that making the issues separately :smiley:

**Comment by smiths** [comment]
Spelling corrections are pushed in a13f1da.

@moalaa is correct, it is better if separate issues are assigned to each reviewer.  It makes it easier to track the conversations, and each reviewer gets the satisfaction of closing an issue.  :smile:

**Comment by smiths** [comment]
Feedback on VnV Plan available in 3c8bdc6.  Since @moalaa has also completed his task, I will close this issue now.
