### ISSUE TITLE
[VnV] Fix Typo 

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#11]
Hello @gabrielasd ,

There is typo mistakes in the intro. Also, try to use hyperref to reference these sections. :smile:

![issue1](https://user-images.githubusercontent.com/31176105/97889153-036fea80-1cfa-11eb-9f35-564e4412ef25.PNG)

**Comment by gabrielasd** [comment]
Addressed in commit a9df3a52c75a97870124498a0a8351562f8502f7
