### ISSUE TITLE
[VnV] SRS Verification Plan 

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#12]
@gabrielasd , I think it will be better to list the approaches that will be used to verify your SRS.
You can check this section in [VnV plan of MISEG](https://github.com/Ao99/MISEG/blob/master/docs/VnVPlan/SystVnVPlan/SystVnVPlan.pdf) may be helpful :smile:

![issue2](https://user-images.githubusercontent.com/31176105/97889676-a32d7880-1cfa-11eb-9b0d-f4cab8eade7f.PNG)

**Comment by gabrielasd** [comment]
Hello @moalaa,
Thanks for the suggestions and the reference. 
I've looked at the reference, but I'm not sure what change I should make. My SRS verification plan is described by a test, SRS Review for which I should have added a hyperlink when I referenced it in this section :( .
Should I remove that test and add its content as a description paragraph under this section?
Do you have any advice Dr @smiths

**Comment by gabrielasd** [comment]
I think Dr. @smiths feedback about this section in the VnV plan complements @moalaa suggestions, so I'll include it here as part of the same issue:
![srsplan](https://user-images.githubusercontent.com/26312264/101594522-d630ef00-39bf-11eb-819b-78deb87ccd53.png)

**Comment by gabrielasd** [comment]
Section made more specific in commit 5e991f517861e7e10b5f4e635ec1247d9f03f48f
