### ISSUE TITLE
[VnV] Design Verification Plan 

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#13]
@gabrielasd, I think the plan is not detailed; For example, it is better to mention how the team will evaluate the verification of your design. 

![issue3](https://user-images.githubusercontent.com/31176105/97890519-9fe6bc80-1cfb-11eb-9361-577c041f96a1.PNG)

**Comment by gabrielasd** [comment]
I've added references to the Module Guide and Interface Specification checklist in commit bfe035acf0d0855d62ed4333b311c3f40c5dddf2
