### ISSUE TITLE
[VnV] Cross References between SRS and VnV

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#14]
@gabrielasd, 
It is a great way in presenting section 4.4 Implementation Verification plan, and using Author's comment to show that unit tests will be added. :thumbsup:
I think it can be enhanced by using cross references between SRS, and VnV, for example, reference IM in SRS here in VnV.
![issue4](https://user-images.githubusercontent.com/31176105/97891714-1f28c000-1cfd-11eb-96d1-cf12db8be7f6.PNG)

**Comment by gabrielasd** [comment]
Yes, I'll add that fix, thanks!
