### ISSUE TITLE
Questions about table 4

### ISSUE THREAD

**Issue by tingyuw** [gabrielasd/eomee#20]
I was wondering are the HOMO and LUMO in this table the expected values for each file? If yes, it will be the expected values for table 3, right?

![image](https://user-images.githubusercontent.com/47548045/98084683-31fcdb00-1e4a-11eb-884c-77e0584c2188.png)

**Comment by gabrielasd** [comment]
Yup you are correct @tingyuw  :). I'll fix this so that it is clear what the purpose of table 4 is.
Thanks for catching this!
