### ISSUE TITLE
EOM as Abstract Class or Interface

### ISSUE THREAD

**Issue by smiths** [gabrielasd/eomee#22]
@gabrielasd, I've been thinking about whether your EOMs should inherit from an abstract class or an interface.  If they are going to share code, then the abstract class makes sense.  Otherwise, you might want to think about an interface.  Googling abstract class versus interface will find many hits.  One that you might find useful is:

https://dzone.com/articles/when-to-use-abstract-class-and-intreface

You can close this issue, once you've had a chance to think about the distinction between abstract classes and interfaces.

**Comment by gabrielasd** [comment]
The implementation of interfaces in Python is different from other languages (https://realpython.com/python-interface/). Using abstract classes (ABC) is one of the forms of implementing them in Python
