### ISSUE TITLE
[MIS] Exceptions in MIS of Input Module

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#27]
Hello Gaby,

I believe you have FileNotFoundError as an exception for both access programs pare_inputfile, and check_inputs, is that correct?
If yes, I suggest to make this exception separated :smile: 
![1](https://user-images.githubusercontent.com/31176105/100032029-0889fc00-2dc5-11eb-9f34-7d9c82a32a55.PNG)

**Comment by gabrielasd** [comment]
This is the type of exception that is raised by Python when it fails to find a file. I didn't use custom names, however, in the code, a message is printed together with the exception to give more context to the user about what happened.
