### ISSUE TITLE
[MG] Trace Between Anticipated Changes and Modules

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#29]
@gabrielasd, for the traceability between anticipated changes and modules, I believe Dr. @smiths mentioned in MG checklists that:
![2](https://user-images.githubusercontent.com/31176105/100630701-df9fc480-32f8-11eb-9ef7-bf305d9ea9a6.PNG)

I believe it is better to edit your likely changes and the matrix according to Dr. smith's comment on the checklist. :smile:
![3](https://user-images.githubusercontent.com/31176105/100630805-fd6d2980-32f8-11eb-8c5d-7390cee23f65.PNG)

**Comment by gabrielasd** [comment]
Thanks for pointing this out :)
I've addressed it in commit 13a8056f0f53cb45a135b6df8b14c0b1c228d8e9
