### ISSUE TITLE
[MG, MIS] Use Hierarchy Between Modules

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#30]
Hello @gabrielasd,

In the Use Hierarchy Between Modules in MG you showed this graph which is perfect for me 👍 
![4](https://user-images.githubusercontent.com/31176105/100631491-c4818480-32f9-11eb-9f04-ee4a16573e33.PNG)

but is it mapped correctly in MIS as I believe control module doesn't use input, integrals, and WfnRDMs, right? 
![3](https://user-images.githubusercontent.com/31176105/100631588-e1b65300-32f9-11eb-8c27-53234af449c0.PNG)

**Comment by gabrielasd** [comment]
This was also a problem detected by Dr Smith:
![useshier1](https://user-images.githubusercontent.com/26312264/102162881-08c36780-3e58-11eb-8f90-b2f32c233fb8.png)
![useshierarchy2](https://user-images.githubusercontent.com/26312264/102162892-0c56ee80-3e58-11eb-9304-6415ad72ab49.png)

It was addressed by commit 05b408fb8220119a28e92e2ba724a70e23ce6a44
