### ISSUE TITLE
EOM requirement specificatios

### ISSUE THREAD

**Issue by gabrielasd** [gabrielasd/eomee#4]
Hi Dr. @smiths I've added the SRS document
You can find it in https://github.com/gabrielasd/eomee/blob/cas741/docs/SRS/SRS.tex
Please let me know what you think of it.

**Comment by smiths** [comment]
@gabrielasd, I have added comments on your SRS to a marked up version of the file in 36e3e5e.  Please create issues from my comments as appropriate.
