### ISSUE TITLE
[SRS] EOM methods as Data Definitions

### ISSUE THREAD

**Issue by gabrielasd** [gabrielasd/eomee#42]
![discuss_comment](https://user-images.githubusercontent.com/26312264/101521100-5705d180-3953-11eb-8a0a-8f632c93faa5.png)

**Comment by gabrielasd** [comment]
Hello Dr. @smiths, 
I introduced the eigenvalue problem as a Data Definition so that I could reference it in the derivation of the EOM equations later on (in the Instance Model section)
![exampleIM](https://user-images.githubusercontent.com/26312264/101522050-b2848f00-3954-11eb-843d-5ea47ca57289.png)


So instead of separate Data Definitions, I had each EOM method be an Instance Model, would it be OK to leave it like that?

**Comment by smiths** [comment]
Yes, having each EOM method as an instance model is better than what I proposed.  :smile:
