### ISSUE TITLE
Abbreviation

### ISSUE THREAD

**Issue by moalaa** [gabrielasd/eomee#5]
Hello Gaby,

I think in the introduction  section, you should state what is EOMEE stands for even if you mentioned it in the abbreviation table as this is the first time to use it.
![sc](https://user-images.githubusercontent.com/31176105/96466860-4c06ae80-11f8-11eb-8425-72fea98bfea7.PNG)

**Comment by gabrielasd** [comment]
You are right @moalaa, thanks for pointing this.

**Comment by smiths** [comment]
@gabrielasd, I like the way that you reference the issues that your commit closes.  In the future, you should consider going even further in this direction by making more commits.  Each issue could receive its own commit for closing the issue.  This improves traceability, and if you ever have to reverse a change, fine-grained commits make it easier.
